// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsRequest) Reset() {
	*x = PostStatsRequest{}
	mi := &file_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsRequest) ProtoMessage() {}

func (x *PostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsRequest.ProtoReflect.Descriptor instead.
func (*PostStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PostStatsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type PostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Views         int64                  `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,3,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsResponse) Reset() {
	*x = PostStatsResponse{}
	mi := &file_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsResponse) ProtoMessage() {}

func (x *PostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsResponse.ProtoReflect.Descriptor instead.
func (*PostStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PostStatsResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostStatsResponse) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *PostStatsResponse) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type TopPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // "views" or "likes"
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsRequest) Reset() {
	*x = TopPostsRequest{}
	mi := &file_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsRequest) ProtoMessage() {}

func (x *TopPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsRequest.ProtoReflect.Descriptor instead.
func (*TopPostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *TopPostsRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TopPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PostItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostItem) Reset() {
	*x = PostItem{}
	mi := &file_proto_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostItem) ProtoMessage() {}

func (x *PostItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostItem.ProtoReflect.Descriptor instead.
func (*PostItem) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *PostItem) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PostItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsResponse) Reset() {
	*x = TopPostsResponse{}
	mi := &file_proto_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsResponse) ProtoMessage() {}

func (x *TopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsResponse.ProtoReflect.Descriptor instead.
func (*TopPostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{4}
}

func (x *TopPostsResponse) GetItems() []*PostItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TopUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersRequest) Reset() {
	*x = TopUsersRequest{}
	mi := &file_proto_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersRequest) ProtoMessage() {}

func (x *TopUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersRequest.ProtoReflect.Descriptor instead.
func (*TopUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{5}
}

func (x *TopUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_proto_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{6}
}

func (x *UserItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserItem) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type TopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserItem            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersResponse) Reset() {
	*x = TopUsersResponse{}
	mi := &file_proto_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersResponse) ProtoMessage() {}

func (x *TopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersResponse.ProtoReflect.Descriptor instead.
func (*TopUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{7}
}

func (x *TopUsersResponse) GetUsers() []*UserItem {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_stats_proto protoreflect.FileDescriptor

const file_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stats.proto\x12\bstats.v1\"+\n" +
	"\x10PostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"X\n" +
	"\x11PostStatsResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05views\x18\x02 \x01(\x03R\x05views\x12\x14\n" +
	"\x05likes\x18\x03 \x01(\x03R\x05likes\"?\n" +
	"\x0fTopPostsRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"9\n" +
	"\bPostItem\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"<\n" +
	"\x10TopPostsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.stats.v1.PostItemR\x05items\"'\n" +
	"\x0fTopUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"9\n" +
	"\bUserItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\x03R\x05likes\"<\n" +
	"\x10TopUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.stats.v1.UserItemR\x05users2\xea\x01\n" +
	"\fStatsService\x12G\n" +
	"\fGetPostStats\x12\x1a.stats.v1.PostStatsRequest\x1a\x1b.stats.v1.PostStatsResponse\x12D\n" +
	"\vGetTopPosts\x12\x19.stats.v1.TopPostsRequest\x1a\x1a.stats.v1.TopPostsResponse\x12K\n" +
	"\x12GetTopUsersByLikes\x12\x19.stats.v1.TopUsersRequest\x1a\x1a.stats.v1.TopUsersResponseB\x1bZ\x19stats-service/proto;protob\x06proto3"

var (
	file_proto_stats_proto_rawDescOnce sync.Once
	file_proto_stats_proto_rawDescData []byte
)

func file_proto_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)))
	})
	return file_proto_stats_proto_rawDescData
}

var file_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_stats_proto_goTypes = []any{
	(*PostStatsRequest)(nil),  // 0: stats.v1.PostStatsRequest
	(*PostStatsResponse)(nil), // 1: stats.v1.PostStatsResponse
	(*TopPostsRequest)(nil),   // 2: stats.v1.TopPostsRequest
	(*PostItem)(nil),          // 3: stats.v1.PostItem
	(*TopPostsResponse)(nil),  // 4: stats.v1.TopPostsResponse
	(*TopUsersRequest)(nil),   // 5: stats.v1.TopUsersRequest
	(*UserItem)(nil),          // 6: stats.v1.UserItem
	(*TopUsersResponse)(nil),  // 7: stats.v1.TopUsersResponse
}
var file_proto_stats_proto_depIdxs = []int32{
	3, // 0: stats.v1.TopPostsResponse.items:type_name -> stats.v1.PostItem
	6, // 1: stats.v1.TopUsersResponse.users:type_name -> stats.v1.UserItem
	0, // 2: stats.v1.StatsService.GetPostStats:input_type -> stats.v1.PostStatsRequest
	2, // 3: stats.v1.StatsService.GetTopPosts:input_type -> stats.v1.TopPostsRequest
	5, // 4: stats.v1.StatsService.GetTopUsersByLikes:input_type -> stats.v1.TopUsersRequest
	1, // 5: stats.v1.StatsService.GetPostStats:output_type -> stats.v1.PostStatsResponse
	4, // 6: stats.v1.StatsService.GetTopPosts:output_type -> stats.v1.TopPostsResponse
	7, // 7: stats.v1.StatsService.GetTopUsersByLikes:output_type -> stats.v1.TopUsersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_stats_proto_init() }
func file_proto_stats_proto_init() {
	if File_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_proto = out.File
	file_proto_stats_proto_goTypes = nil
	file_proto_stats_proto_depIdxs = nil
}
